CodeQ:
  AssetSearch:
    elasticSearch:
      indexName: 'assets'
      command:
        useSubProcesses: true
    indexing:
      realtimeIndexing:
        enabled: true
      batchSize:
        elements: 500
        octets: 40000000
      assetExtraction:
        # The maximum size of files to be ingested in bytes (100 Mb)
        maximumFileSize: 104857600
      mapping:
        properties:
          'neos_fulltext_parts':
            type: object
            enabled: false
          'neos_fulltext':
            type: object
            properties:
              'h1':
                type: text
              'h2':
                type: text
              'h3':
                type: text
              'h4':
                type: text
              'h5':
                type: text
              'h6':
                type: text
              'text':
                type: text
          'last_modified':
            type: date
            format: 'date_time_no_millis'
          caption:
            type: keyword
          'copyright_notice':
            type: keyword
          content:
            type: keyword
          title:
            type: keyword
          name:
            type: keyword
          author:
            type: keyword
          date:
            type: date
            format: 'date_time_no_millis'
          contentType:
            type: keyword
          contentLength:
            type: keyword
          language:
            type: keyword
          tags:
            type: keyword
          collections:
            type: keyword
    driver:
      version: '6.x'
      mapping:
        6.x: &v6x
          query:
            className: CodeQ\AssetSearch\Driver\Version6\Query\FilteredQuery
            arguments:
              request:
                query:
                  bool:
                    must:
                      - match_all:
                          boost: 1.0 # force match_all to be an object
                    filter:
                      bool:
                        must: [ ]
                        should: [ ]
                        must_not: [ ]
                _source:
                  - 'neos_path'

              unsupportedFieldsInCountRequest:
                - '_source'
                - 'sort'
                - 'from'
                - 'size'
                - 'highlight'
                - 'aggs'
                - 'aggregations'
                - 'suggest'

              # Parameters for the query string query used by the fullText() operation
              # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-multi-field
              # for all available parameters
              queryStringParameters:
                default_operator: or
                fields:
                  - neos_fulltext.h1^20
                  - neos_fulltext.h2^12
                  - neos_fulltext.h3^10
                  - neos_fulltext.h4^5
                  - neos_fulltext.h5^3
                  - neos_fulltext.h6^2
                  - neos_fulltext.text^1

          document:
            className: 'CodeQ\AssetSearch\Driver\Version6\DocumentDriver'
          indexer:
            className: 'CodeQ\AssetSearch\Driver\Version6\IndexerDriver'
          indexManagement:
            className: 'CodeQ\AssetSearch\Driver\Version6\IndexDriver'
          request:
            className: 'CodeQ\AssetSearch\Driver\Version6\RequestDriver'
          system:
            className: 'CodeQ\AssetSearch\Driver\Version6\SystemDriver'
          assetMappingBuilder:
            className: 'CodeQ\AssetSearch\Driver\Version6\Mapping\AssetMappingBuilder'
        7.x: *v6x

Neos:
  Fusion:
    defaultContext:
      AssetSearch.Search: CodeQ\AssetSearch\Eel\SearchHelper
      AssetSearch.Collection: CodeQ\AssetSearch\Eel\AssetCollectionHelper
      AssetSearch.Tag: CodeQ\AssetSearch\Eel\AssetTagHelper
